# Generated by Django 5.2.14 on 2026-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsubi_zaiko', '0013_equipmentitem_item_kind_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_drawing_root_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='金型図面親フォルダ'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_drawing_subfolder_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='金型図面サブフォルダ'),
        ),
    ]
