# Generated by Django 5.2.14 on 2026-05-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsubi_zaiko', '0014_equipmentitem_mold_drawing_root_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment_document_root_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='設備資料親フォルダ'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment_document_subfolder_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='設備資料サブフォルダ'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment_group_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='設備グループ'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment_series_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='設備シリーズ・型式分類'),
        ),
    ]
