# Generated by Django 5.2.14 on 2026-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsubi_zaiko', '0015_equipmentitem_equipment_document_root_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_component_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='金型部品・構成品名'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_customer_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='金型顧客コード'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='金型顧客名'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_product_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='金型製品コード'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='mold_product_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='金型製品名'),
        ),
    ]
