# Generated by Django 5.2.14 on 2026-05-28 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsubi_zaiko', '0016_equipmentitem_mold_component_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCatalogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='カタログコード')),
                ('name', models.CharField(max_length=160, verbose_name='カタログ名')),
                ('item_kind', models.CharField(choices=[('equipment', '設備台帳'), ('mold', '金型台帳')], max_length=20, verbose_name='管理区分')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='setsubi_zaiko.equipmentcatalognode', verbose_name='親カタログ')),
            ],
            options={
                'verbose_name': '設備・金型カタログ',
                'verbose_name_plural': '設備・金型カタログ',
                'ordering': ['item_kind', 'sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='catalog_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='setsubi_zaiko.equipmentcatalognode', verbose_name='設備・金型カタログ'),
        ),
    ]
