# Generated by Django 5.2.15 on 2026-07-03 01:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0072_expand_maillog_lengths'),
        ('setsubi_zaiko', '0017_equipmentcatalognode_equipmentitem_catalog_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpartlink',
            name='baseline_shot',
            field=models.PositiveBigIntegerField(default=0, verbose_name='交換時累積shot'),
        ),
        migrations.AddField(
            model_name='equipmentpartlink',
            name='last_replaced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終交換日'),
        ),
        migrations.AddField(
            model_name='equipmentpartlink',
            name='lifetime_shots',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='交換目安(shot)'),
        ),
        migrations.AddField(
            model_name='equipmentpartlink',
            name='shot_source_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setsubi_part_links', to='iot.machine', verbose_name='成形機shot元'),
        ),
        migrations.AddField(
            model_name='equipmentpartlink',
            name='shot_source_mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setsubi_part_links', to='iot.moldlifetime', verbose_name='金型shot元'),
        ),
        migrations.CreateModel(
            name='EquipmentPartReplacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='今回交換日')),
                ('previous_replaced_at', models.DateTimeField(blank=True, null=True, verbose_name='前回交換日')),
                ('shot_at_replacement', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='交換時累積shot')),
                ('baseline_shot_before', models.PositiveBigIntegerField(default=0, verbose_name='前回基準shot')),
                ('used_shots', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='使用shot数')),
                ('note', models.TextField(blank=True, verbose_name='交換メモ')),
                ('operator_name', models.CharField(blank=True, max_length=120, verbose_name='交換作業者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_part_replacement_histories', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_histories', to='setsubi_zaiko.equipmentpartlink', verbose_name='設備・金型 使用部品')),
            ],
            options={
                'verbose_name': '部品交換履歴',
                'verbose_name_plural': '部品交換履歴',
                'ordering': ['-replaced_at', '-id'],
            },
        ),
    ]
