# Generated by Django 5.2.15 on 2026-07-03 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0072_expand_maillog_lengths'),
        ('setsubi_zaiko', '0018_equipmentpartlink_baseline_shot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='iot_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setsubi_assets', to='iot.machine', verbose_name='IoT成形機shot連携'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='iot_mold_lifetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setsubi_assets', to='iot.moldlifetime', verbose_name='IoT金型shot連携'),
        ),
    ]
