# Generated by Django 5.2.15 on 2026-07-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0073_esp32cardsnapshot_total_shot'),
        ('setsubi_zaiko', '0019_equipmentitem_iot_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='iot_esp32_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setsubi_assets', to='iot.esp32cardsnapshot', verbose_name='ESP32成形機shot連携'),
        ),
    ]
