# Generated by Django 5.1.6 on 2025-04-14 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Nhiệm Vụ')),
                ('code', models.CharField(max_length=50, verbose_name='Mã Nhiệm Vụ')),
                ('machine_count', models.IntegerField(verbose_name='Số Lượng Máy')),
                ('quantity', models.CharField(blank=True, default='Không xác định', max_length=50, null=True, verbose_name='Số Lượng')),
                ('material', models.CharField(blank=True, default='Không xác định', max_length=50, null=True, verbose_name='Vật Liệu')),
                ('maintenance_frequency', models.CharField(blank=True, default='Hàng tháng', max_length=50, null=True, verbose_name='Tần Suất Bảo Trì')),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Hình Ảnh Nhiệm Vụ')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Hình Ảnh Sản Phẩm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Gian Tạo')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Nhiệm Vụ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Gian Tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_codes', to='baotri.maintenancetask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Tên Công Việc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô Tả')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='task_details/', verbose_name='Hình Ảnh Tham Khảo')),
                ('drawing_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kích Thước')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='baotri.maintenancetask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Kết Quả')),
                ('actual_image', models.ImageField(blank=True, null=True, upload_to='actual_images/', verbose_name='Hình Ảnh Thực Tế')),
                ('actual_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kích Thước Thực Tế')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Đã Xác Nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời Gian Tạo')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='baotri.taskdetail')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người Bảo Trì')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='baotri.maintenancetask')),
            ],
        ),
    ]
