# Generated by Django 5.1.6 on 2025-04-17 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='code',
            field=models.CharField(max_length=50, verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='machine_count',
            field=models.IntegerField(verbose_name='機械番号'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='maintenance_frequency',
            field=models.CharField(blank=True, default='毎月', max_length=50, null=True, verbose_name='メンテナンス頻度'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='material',
            field=models.CharField(blank=True, default='未定義', max_length=50, null=True, verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='製品名'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='金型画像'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='quantity',
            field=models.CharField(blank=True, default='未定義', max_length=50, null=True, verbose_name='取数'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='製品画像'),
        ),
        migrations.AlterField(
            model_name='taskcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='taskcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='taskcode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='drawing_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='寸法'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='item',
            field=models.CharField(max_length=255, verbose_name='作業名'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_details/', verbose_name='参考画像'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='actual_image',
            field=models.ImageField(blank=True, null=True, upload_to='actual_images/', verbose_name='実際の画像'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='actual_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='実際の寸法'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='確認済み'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='result',
            field=models.TextField(verbose_name='結果'),
        ),
        migrations.CreateModel(
            name='TaskCodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True, verbose_name='結果')),
                ('actual_image', models.ImageField(blank=True, null=True, upload_to='task_code_details/', verbose_name='実際の写真')),
                ('actual_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='実際の寸法')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確認済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_code_details', to='baotri.taskdetail', verbose_name='作業詳細')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('task_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='baotri.taskcode', verbose_name='タスクコード')),
            ],
        ),
    ]
