# Generated by Django 5.1.6 on 2025-04-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0002_alter_maintenancetask_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
