# Generated by Django 5.1.6 on 2025-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0003_taskcode_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
