# Generated by Django 5.1.6 on 2025-07-31 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0004_taskdetail_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcode',
            name='is_confirmed_by_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcode',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcode',
            name='supervisor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcode',
            name='supervisor_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
    ]
