# Generated by Django 5.1.6 on 2025-07-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0005_taskcode_is_confirmed_by_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcode',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
