# Generated by Django 5.1.6 on 2025-08-04 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0006_taskcode_supervisor_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='内容・原因')),
                ('solution', models.TextField(blank=True, verbose_name='対策')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='mistake_images/', verbose_name='参考画像1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='mistake_images/', verbose_name='参考画像2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='mistake_images/', verbose_name='参考画像3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='mistake_images/', verbose_name='参考画像4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baotri.taskcodedetail')),
                ('task_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='baotri.taskcode')),
            ],
        ),
    ]
