# Generated by Django 5.1.6 on 2025-08-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0007_maintenancemistake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemistake',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='maintenancemistake',
            name='task_code',
        ),
        migrations.AddField(
            model_name='maintenancemistake',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baotri.maintenancetask', verbose_name='製品'),
        ),
    ]
