# Generated by Django 5.1.6 on 2025-08-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0008_remove_maintenancemistake_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcodedetail',
            name='counter_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='カウンター総数'),
        ),
    ]
