# Generated by Django 5.1.6 on 2025-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0009_taskcodedetail_counter_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcode',
            name='counter_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='カウンター総数'),
        ),
    ]
