# Generated by Django 5.1.6 on 2025-08-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baotri', '0010_taskcode_counter_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
