# Generated by Django 5.1.6 on 2025-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
