# Generated by Django 5.1.6 on 2025-03-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='subcontents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subtitles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
