# Generated by Django 5.1.6 on 2025-03-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_subcontents_newsarticle_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='subcontents',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='subtitles',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subcontent1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subcontent2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subcontent3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subtitle3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
