# Generated by Django 5.1.6 on 2025-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsarticle_subcontents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
