# Generated by Django 5.1.6 on 2025-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='setsubi_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='設備管理No'),
        ),
    ]
