# Generated by Django 5.1.6 on 2025-07-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_machine_setsubi_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='部品コード')),
                ('name', models.CharField(max_length=100, verbose_name='部品名')),
                ('lifetime', models.PositiveIntegerField(verbose_name='部品寿命（ショット数）')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='iot.machine')),
            ],
        ),
    ]
