# Generated by Django 5.1.6 on 2025-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='部品詳細'),
        ),
    ]
