# Generated by Django 5.1.6 on 2025-07-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_component_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型式'),
        ),
    ]
