# Generated by Django 5.1.6 on 2025-07-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_machine_manufacturer_machine_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentReplacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('image', models.ImageField(blank=True, null=True, upload_to='component_replacements/')),
                ('confirmed_by', models.CharField(blank=True, max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_histories', to='iot.component')),
            ],
        ),
    ]
