# Generated by Django 5.1.6 on 2025-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_componentreplacementhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentreplacementhistory',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='component_replacements/'),
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='component_replacements/'),
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='component_replacements/'),
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='component_replacements/'),
        ),
    ]
