# Generated by Django 5.1.6 on 2025-08-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_rename_image_componentreplacementhistory_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoldLifetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condname', models.CharField(max_length=100)),
                ('total_shot', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.mold')),
            ],
        ),
    ]
