# Generated by Django 5.1.6 on 2025-08-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_mold_moldlifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldlifetime',
            name='last_shotno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
