# Generated by Django 5.1.6 on 2025-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_moldlifetime_last_shotno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condname', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
