# Generated by Django 5.1.6 on 2025-08-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_cyclehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclehistory',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
