# Generated by Django 5.1.6 on 2025-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_alter_cyclehistory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moldlifetime',
            name='last_shotno',
        ),
        migrations.AddField(
            model_name='moldlifetime',
            name='lifetime',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='moldlifetime',
            name='total_shot',
            field=models.IntegerField(default=0),
        ),
    ]
