# Generated by Django 5.1.6 on 2025-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_remove_moldlifetime_last_shotno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mold',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='金型品番'),
        ),
    ]
