# Generated by Django 5.1.6 on 2025-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_mold_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mold',
            name='status',
            field=models.CharField(choices=[('active', '生産中'), ('inactive', '生産終了')], default='active', max_length=10, verbose_name='状態'),
        ),
    ]
