# Generated by Django 5.1.6 on 2025-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_mold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cycle_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='shot_24h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='shot_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('production', '稼働中'), ('inactive', '停止')], default='inactive', max_length=20),
        ),
    ]
