# Generated by Django 5.1.6 on 2025-08-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_machine_cycle_time_machine_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_shot',
            field=models.IntegerField(default=0),
        ),
    ]
