# Generated by Django 5.1.6 on 2025-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_machine_last_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldlifetime',
            name='last_shot',
            field=models.IntegerField(default=0),
        ),
    ]
