# Generated by Django 5.1.6 on 2025-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_moldlifetime_last_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condname', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='manual', max_length=50)),
                ('shotno', models.IntegerField(default=0)),
                ('cycletime', models.FloatField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
