# Generated by Django 5.1.6 on 2025-09-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_manualmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='iot.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'is_active'], name='iot_alarm_machine_cdbd8f_idx'), models.Index(fields=['code'], name='iot_alarm_code_08473b_idx'), models.Index(fields=['-last_seen'], name='iot_alarm_last_se_b81477_idx')],
            },
        ),
    ]
