# Generated by Django 5.1.6 on 2025-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0019_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_address', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('quality_rate', models.FloatField(blank=True, null=True)),
                ('good_shots', models.IntegerField(blank=True, null=True)),
                ('total_shots', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('machine_address', 'year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
