# Generated by Django 5.1.6 on 2025-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0020_machinequality_delete_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinequality',
            name='good_shots',
        ),
        migrations.RemoveField(
            model_name='machinequality',
            name='quality_rate',
        ),
        migrations.RemoveField(
            model_name='machinequality',
            name='total_shots',
        ),
        migrations.AddField(
            model_name='machinequality',
            name='defect_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machinequality',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='machinequality',
            name='produced_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machinequality',
            name='machine_address',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
