# Generated by Django 5.1.6 on 2025-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0021_remove_machinequality_good_shots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='baseline_shot',
            field=models.IntegerField(default=0, help_text='Shot của máy tại thời điểm lắp / thay mới'),
        ),
        migrations.AddField(
            model_name='component',
            name='predicted_next_replacement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
