# Generated by Django 5.1.6 on 2025-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0022_component_baseline_shot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentreplacementhistory',
            options={'ordering': ['-replaced_at']},
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='component_attachments/'),
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='baseline_shot_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentreplacementhistory',
            name='shot_at_replacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='confirmed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='component_replace/'),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='component_replace/'),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='component_replace/'),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='component_replace/'),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='component_replace/'),
        ),
        migrations.AlterField(
            model_name='componentreplacementhistory',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
