# Generated by Django 5.1.6 on 2025-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0023_alter_componentreplacementhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='management_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='管理コード'),
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='部品メーカー'),
        ),
        migrations.AddField(
            model_name='component',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
