# Generated by Django 5.1.6 on 2025-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0024_component_management_code_component_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='cycle_time',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='shot_24h',
        ),
        migrations.AddField(
            model_name='machine',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='IP/Address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='condname',
            field=models.CharField(blank=True, max_length=100, verbose_name='成形条件名'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='last_shot',
            field=models.PositiveIntegerField(default=0, verbose_name='Last Shot(DB)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='機械名'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shot_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Shot Total(DB)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(blank=True, default='production', max_length=20, verbose_name='状態'),
        ),
    ]
