# Generated by Django 5.1.6 on 2025-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0025_remove_machine_cycle_time_remove_machine_shot_24h_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclehistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='machinequality',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='component',
            name='baseline_shot',
            field=models.IntegerField(db_index=True, default=0, help_text='Shot của máy tại thời điểm lắp / thay mới'),
        ),
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='部品コード'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='address',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='IP/Address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='setsubi_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='設備管理No'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='production', max_length=20, verbose_name='状態'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['code'], name='iot_compone_code_a03545_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['management_code'], name='iot_compone_managem_2a612c_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['baseline_shot'], name='iot_compone_baselin_f817ff_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='iot_machine_status_a0d97e_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['active'], name='iot_machine_active_d03863_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['setsubi_no'], name='iot_machine_setsubi_18d144_idx'),
        ),
    ]
