# Generated by Django 5.1.6 on 2025-09-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0026_alter_cyclehistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineQuality',
        ),
    ]
