# Generated by Django 5.1.6 on 2025-09-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0027_delete_machinequality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionPlan',
        ),
    ]
