# Generated by Django 5.1.6 on 2025-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0028_delete_productionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoPinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pin3', models.IntegerField(blank=True, null=True)),
                ('pin6', models.IntegerField(blank=True, null=True)),
                ('pin7', models.IntegerField(blank=True, null=True)),
                ('pin8', models.IntegerField(blank=True, null=True)),
                ('pin9', models.IntegerField(blank=True, null=True)),
                ('pin10', models.IntegerField(blank=True, null=True)),
                ('pin11', models.IntegerField(blank=True, null=True)),
                ('pin12', models.IntegerField(blank=True, null=True)),
                ('A0', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
