# Generated by Django 5.1.6 on 2025-09-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0029_arduinopinlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_code', models.CharField(max_length=20)),
                ('alarm_name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('reset_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('raw_line', models.TextField(blank=True, default='')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='iot.machine')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['machine', 'active'], name='iot_machine_machine_4bc706_idx'), models.Index(fields=['started_at'], name='iot_machine_started_aff7ab_idx')],
            },
        ),
    ]
