# Generated by Django 5.1.6 on 2025-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0030_machinealarmevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinealarmevent',
            name='alarm_category',
            field=models.CharField(blank=True, db_index=True, max_length=1),
        ),
        migrations.AddField(
            model_name='machinealarmevent',
            name='alarm_category_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='machinealarmevent',
            index=models.Index(fields=['alarm_category'], name='iot_machine_alarm_c_404ddd_idx'),
        ),
    ]
