# Generated by Django 5.1.6 on 2025-09-08 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0031_machinealarmevent_alarm_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('production', '稼働中'), ('stop', '停止'), ('arrange', '段取り中'), ('alarm', 'アラーム'), ('offline', 'オフライン'), ('unknown', '不明')], max_length=16)),
                ('status_jp', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='machinealarmevent',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='machinealarmevent',
            name='iot_machine_machine_4bc706_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinealarmevent',
            name='iot_machine_started_aff7ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinealarmevent',
            name='iot_machine_alarm_c_404ddd_idx',
        ),
        migrations.RenameField(
            model_name='machinealarmevent',
            old_name='reset_at',
            new_name='cleared_at',
        ),
        migrations.RemoveField(
            model_name='machinealarmevent',
            name='active',
        ),
        migrations.RemoveField(
            model_name='machinealarmevent',
            name='alarm_category',
        ),
        migrations.RemoveField(
            model_name='machinealarmevent',
            name='alarm_category_label',
        ),
        migrations.RemoveField(
            model_name='machinealarmevent',
            name='raw_line',
        ),
        migrations.RemoveField(
            model_name='machinealarmevent',
            name='started_at',
        ),
        migrations.AddField(
            model_name='machinealarmevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='machinealarmevent',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='machinealarmevent',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='machinealarmevent',
            name='alarm_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='machinealarmevent',
            name='alarm_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='machinealarmevent',
            index=models.Index(fields=['created_at'], name='iot_machine_created_e911bf_idx'),
        ),
        migrations.AddIndex(
            model_name='machinealarmevent',
            index=models.Index(fields=['cleared_at'], name='iot_machine_cleared_cad6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='machinealarmevent',
            index=models.Index(fields=['alarm_code'], name='iot_machine_alarm_c_5c2701_idx'),
        ),
        migrations.AddField(
            model_name='machinestatusevent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='iot.machine'),
        ),
        migrations.AddIndex(
            model_name='machinestatusevent',
            index=models.Index(fields=['created_at', 'status_code'], name='iot_machine_created_9ef4f7_idx'),
        ),
    ]
