# Generated by Django 5.1.6 on 2025-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0032_machinestatusevent_alter_machinealarmevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='mail', max_length=64)),
                ('is_alarm', models.BooleanField(default=False)),
            ],
        ),
    ]
