# Generated by Django 5.1.6 on 2025-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0033_dashboardnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardnotification',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
