# Generated by Django 5.1.6 on 2025-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0034_dashboardnotification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_uid', models.CharField(max_length=128, unique=True)),
                ('sender', models.CharField(blank=True, max_length=128)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('received_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
