# Generated by Django 5.1.6 on 2025-09-16 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0035_maillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardnotification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dashboardnotification',
            name='source',
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='appear_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboardnotification',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
