# Generated by Django 5.1.6 on 2025-09-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0036_remove_dashboardnotification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demalarms', to='iot.machine')),
            ],
            options={
                'unique_together': {('machine',)},
            },
        ),
    ]
