# Generated by Django 5.1.6 on 2025-09-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0038_esp32device_esp32statuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_code', models.CharField(blank=True, max_length=32, null=True)),
                ('alarm_name', models.CharField(blank=True, max_length=128, null=True)),
                ('alarm_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='iot.esp32device')),
            ],
        ),
    ]
