# Generated by Django 5.1.6 on 2025-09-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0039_esp32alarmevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32alarmevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.esp32device'),
        ),
    ]
