# Generated by Django 5.1.6 on 2025-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0040_alter_esp32alarmevent_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32AlarmCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
