# Generated by Django 5.1.6 on 2025-10-03 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0041_esp32alarmcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemAlarmMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demalarm_monthly', to='iot.machine')),
            ],
            options={
                'unique_together': {('machine', 'year', 'month')},
            },
        ),
    ]
