# Generated by Django 5.1.6 on 2025-10-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0042_demalarmmonthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demalarm',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='demalarm',
            name='last_update_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demalarm',
            name='last_update_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demalarm',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.machine'),
        ),
        migrations.DeleteModel(
            name='DemAlarmMonthly',
        ),
    ]
