# Generated by Django 5.1.6 on 2025-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0043_remove_demalarm_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32CycleShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, unique=True)),
                ('shot', models.PositiveIntegerField(default=0)),
                ('cycletime', models.FloatField(default=0.0)),
                ('last_ej_on', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
