# Generated by Django 5.1.6 on 2025-10-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0044_esp32cycleshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32alarmcount',
            name='last_update_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='esp32alarmcount',
            name='last_update_year',
            field=models.IntegerField(default=0),
        ),
    ]
