# Generated by Django 5.1.6 on 2025-10-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0046_productionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
