# Generated by Django 5.1.6 on 2025-10-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0047_productionplan_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='plan_created_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='plan_month_year',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
