# Generated by Django 5.1.6 on 2025-10-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0048_remove_productionplan_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='cell_note',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
