# Generated by Django 5.1.6 on 2025-10-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0049_productionplan_cell_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='note_color',
            field=models.CharField(blank=True, default='bg-success', max_length=32),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='note_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
