# Generated by Django 5.1.6 on 2025-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0050_productionplan_note_color_productionplan_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='note_type',
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='note_color',
            field=models.CharField(blank=True, default='bg-secondary', max_length=32),
        ),
    ]
