# Generated by Django 5.1.6 on 2025-10-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0051_remove_productionplan_note_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32alarmcount',
            name='last_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='esp32alarmcount',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
