# Generated by Django 5.1.6 on 2025-10-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0052_esp32alarmcount_last_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32alarmcount',
            name='last_status_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
