# Generated by Django 5.1.6 on 2025-11-28 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0053_esp32alarmcount_last_status_change_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change4MEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='4M', max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('reporter', models.CharField(blank=True, default='', max_length=128)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma or Japanese comma separated tags', max_length=512)),
                ('highlight', models.BooleanField(default=False)),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active_from', '-created_at'],
            },
        ),
    ]
