# Generated by Django 5.1.6 on 2025-12-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0054_change4mentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldlifetime',
            name='esp32_product_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='moldlifetime',
            name='condname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moldlifetime',
            name='mold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifetimes', to='iot.mold'),
        ),
        migrations.AlterField(
            model_name='moldlifetime',
            name='total_shot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
