# Generated by Django 5.1.6 on 2025-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0055_moldlifetime_esp32_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldlifetime',
            name='esp32_machine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
