# Generated by Django 5.1.6 on 2025-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0056_moldlifetime_esp32_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32CardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, unique=True)),
                ('product_display', models.CharField(blank=True, default='', max_length=255)),
                ('primary_product', models.CharField(blank=True, default='', max_length=150)),
                ('shot', models.IntegerField(default=0)),
                ('cycletime', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
