# Generated by Django 5.1.6 on 2025-12-03 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0057_esp32cardsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatworkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ内容')),
                ('sender', models.CharField(blank=True, default='', max_length=128, verbose_name='送信者')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='受信日時')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='画像URL')),
                ('room_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ルームID')),
                ('message_id', models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='メッセージID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time', '-created_at'],
            },
        ),
    ]
