# Generated by Django 5.1.6 on 2025-12-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0058_chatworkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkmessage',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
