# Generated by Django 5.1.6 on 2025-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0059_chatworkmessage_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatworkmessage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
