# Generated by Django 5.1.6 on 2025-12-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0060_alter_chatworkmessage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatworkmessage',
            name='file_url',
        ),
    ]
