# Generated by Django 5.1.6 on 2025-12-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0061_remove_chatworkmessage_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32alarmcount',
            name='alarm_sent_this_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='esp32alarmcount',
            name='address',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='esp32alarmcount',
            name='last_status',
            field=models.CharField(default='', max_length=16),
        ),
    ]
