# Generated by Django 5.1.6 on 2025-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0062_esp32alarmcount_alarm_sent_this_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32cycleshot',
            name='shotplan',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Tổng số shot kế hoạch trong tháng'),
        ),
    ]
