# Generated by Django 5.1.6 on 2025-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0063_esp32cycleshot_shotplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShotMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(db_index=True, max_length=64)),
                ('product_name', models.CharField(db_index=True, max_length=128)),
                ('standard_shot', models.PositiveIntegerField(default=0, help_text='Giá trị shot chuẩn cho sản phẩm này trên máy này')),
                ('kodori', models.PositiveIntegerField(db_index=True, default=1, help_text='Số lượng sản phẩm trong 1 shot')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'unique_together': {('machine', 'product_name')},
            },
        ),
    ]
