# Generated by Django 5.1.6 on 2025-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0064_productshotmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32cycleshot',
            name='current_product',
            field=models.CharField(db_index=True, default='', help_text='Tên sản phẩm hiện tại', max_length=100),
        ),
    ]
