# Generated by Django 5.1.6 on 2025-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0065_esp32cycleshot_current_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net100CycleShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=20)),
                ('shot', models.PositiveIntegerField(default=0)),
                ('cycletime', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shotplan', models.PositiveIntegerField(db_index=True, default=0, help_text='Tổng số shot kế hoạch trong tháng')),
                ('current_product', models.CharField(db_index=True, default='', help_text='Tên sản phẩm hiện tại', max_length=100)),
                ('month', models.CharField(db_index=True, max_length=7)),
            ],
        ),
    ]
