# Generated by Django 5.1.6 on 2025-12-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0066_net100cycleshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='net100cycleshot',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
