# Generated by Django 5.1.6 on 2026-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0067_net100cycleshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='net100cycleshot',
            name='monthly_shot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
