# Generated by Django 5.1.6 on 2026-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0068_net100cycleshot_monthly_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32cycleshot',
            name='month',
            field=models.CharField(db_index=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='esp32cycleshot',
            name='monthly_shot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
