# Generated by Django 5.1.6 on 2026-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0069_esp32cycleshot_month_esp32cycleshot_monthly_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMonthlyShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('net100', 'NET100'), ('esp32', 'ESP32')], max_length=10)),
                ('address', models.CharField(db_index=True, max_length=20)),
                ('machine_name', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(db_index=True, max_length=100)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('shot', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('source', 'address', 'product_name', 'month')},
            },
        ),
    ]
