# Generated by Django 5.1.6 on 2026-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0070_productmonthlyshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change4mentry',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='タグをカンマ(,)または読点(、)で区切って複数指定できます。', max_length=512),
        ),
    ]
