# Generated by Django 5.2.15 on 2026-07-03 06:00

from django.db import migrations, models


def initialize_esp32_machine_total_shot(apps, schema_editor):
    Esp32CardSnapshot = apps.get_model('iot', 'Esp32CardSnapshot')
    MoldLifetime = apps.get_model('iot', 'MoldLifetime')

    mold_by_machine = {}
    mold_by_product = {}
    for lifetime in MoldLifetime.objects.select_related('mold').all():
        machine_key = (lifetime.esp32_machine or '').strip()
        if machine_key and machine_key not in mold_by_machine:
            mold_by_machine[machine_key] = lifetime
        product_key = (lifetime.esp32_product_name or lifetime.mold.name or '').strip().lower()
        if product_key and product_key not in mold_by_product:
            mold_by_product[product_key] = lifetime

    for snapshot in Esp32CardSnapshot.objects.all():
        lifetime = mold_by_machine.get((snapshot.address or '').strip())
        if lifetime is None:
            product_key = (snapshot.primary_product or snapshot.product_display or '').strip().lower()
            lifetime = mold_by_product.get(product_key)
        if lifetime is not None:
            snapshot.total_shot = max(int(lifetime.total_shot or 0), 0)
            snapshot.save(update_fields=['total_shot'])


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0072_expand_maillog_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32cardsnapshot',
            name='total_shot',
            field=models.PositiveBigIntegerField(default=0, help_text='Shot tích lũy của máy ESP32, cộng theo shot khuôn đang chạy'),
        ),
        migrations.RunPython(initialize_esp32_machine_total_shot, migrations.RunPython.noop),
    ]
