# Generated by Django 5.2.15 on 2026-07-03 06:04

from django.db import migrations, models


def initialize_esp32_counter_checkpoint(apps, schema_editor):
    Esp32CardSnapshot = apps.get_model('iot', 'Esp32CardSnapshot')
    for snapshot in Esp32CardSnapshot.objects.all():
        current_shot = max(int(snapshot.shot or 0), 0)
        update_fields = ['last_counted_shot']
        snapshot.last_counted_shot = current_shot
        if not snapshot.total_shot:
            snapshot.total_shot = current_shot
            update_fields.append('total_shot')
        snapshot.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0073_esp32cardsnapshot_total_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32cardsnapshot',
            name='last_counted_shot',
            field=models.PositiveIntegerField(default=0, help_text='Counter ESP32 đã dùng ở lần cộng dồn gần nhất'),
        ),
        migrations.RunPython(initialize_esp32_counter_checkpoint, migrations.RunPython.noop),
    ]
