# Generated by Django 5.1.6 on 2025-04-04 07:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('machine_count', models.IntegerField()),
                ('creator', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('mold_image', models.ImageField(blank=True, null=True, upload_to='mold_images/')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuKiemTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='lich_su_kiem_tra/reference_images/')),
                ('current_image', models.ImageField(blank=True, null=True, upload_to='lich_su_kiem_tra/current_images/')),
                ('drawing_size', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_size', models.CharField(blank=True, max_length=255, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_kiem_tra', to='mente.product')),
            ],
        ),
        migrations.CreateModel(
            name='Checksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='reference_images/')),
                ('current_image', models.ImageField(blank=True, null=True, upload_to='current_images/')),
                ('drawing_size', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_size', models.CharField(blank=True, max_length=100, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Đạt', 'Đạt'), ('Không đạt', 'Không đạt')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checksheets', to='mente.product')),
            ],
        ),
    ]
