# Generated by Django 5.1.6 on 2025-04-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maintenance_frequency',
            field=models.CharField(blank=True, default='毎月', max_length=50, null=True, verbose_name='メンテナンス頻度'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='未設定', max_length=50, null=True, verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, default='2個取り', max_length=50, null=True, verbose_name='取数'),
        ),
    ]
