# Generated by Django 5.1.6 on 2025-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mente', '0003_alter_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsukiemtra',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='lichsukiemtra',
            name='start_time',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
    ]
