# Generated by Django 5.1.6 on 2025-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_chu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('社員', '社員'), ('リーダー', 'リーダー'), ('係長', '係長'), ('課長', '課長'), ('部長', '部長')], default='社員', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
