# Generated by Django 5.1.6 on 2025-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_chu', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('社員', '社員'), ('リーダー', 'リーダー'), ('係長', '係長'), ('課長', '課長'), ('部長', '部長')], default='社員', max_length=50),
        ),
    ]
