# Generated by Django 5.1.6 on 2025-06-19 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MayTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_may', models.CharField(max_length=100, unique=True)),
                ('ten_hien_thi', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255)),
                ('nguoi_phu_trach', models.CharField(blank=True, max_length=100)),
                ('trang_thai', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChuongTrinhNhapLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuong_trinh', models.CharField(max_length=255, unique=True)),
                ('dong1', models.CharField(blank=True, max_length=255)),
                ('dong2', models.CharField(blank=True, max_length=255)),
                ('dong3', models.CharField(blank=True, max_length=255)),
                ('dong4', models.CharField(blank=True, max_length=255)),
                ('dong5', models.CharField(blank=True, max_length=255)),
                ('quy_tac', models.TextField(help_text='Lưu thứ tự nhập liệu, dạng JSON hoặc text')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thiet_ke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
