# Generated by Django 5.1.6 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhap_lieu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KetQuaNhapLieu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_may", models.CharField(db_index=True, help_text="IP máy gửi dữ liệu", max_length=45)),
                ("ma_nhap_lieu", models.TextField(help_text="Dữ liệu text được copy từ app")),
                ("full_text", models.TextField(blank=True, help_text="Toàn bộ text (nếu có)")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Chờ xử lý", "Chờ xử lý"), ("Thành công", "Thành công"), ("Lỗi", "Lỗi")],
                        db_index=True,
                        default="Chờ xử lý",
                        max_length=50,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True)),
                ("ngay_nhan", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "chuong_trinh",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="nhap_lieu.chuongtrinhnhaplieu"),
                ),
                (
                    "may_tinh",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="nhap_lieu.maytinh"),
                ),
            ],
            options={
                "verbose_name_plural": "Kết quả nhập liệu",
                "ordering": ["-ngay_nhan"],
            },
        ),
        migrations.AddIndex(
            model_name="ketquanhaplieu",
            index=models.Index(fields=["ip_may", "-ngay_nhan"], name="nhap_lieu_k_ip_may_8ec80c_idx"),
        ),
        migrations.AddIndex(
            model_name="ketquanhaplieu",
            index=models.Index(fields=["trang_thai", "-ngay_nhan"], name="nhap_lieu_k_trang_t_d50c3f_idx"),
        ),
    ]
