# Generated by Django 5.1.6 on 2026-03-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhap_lieu', '0002_ketquanhaplieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhienNhapLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_job', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_may', models.CharField(db_index=True, max_length=45)),
                ('payload_json', models.TextField(blank=True)),
                ('trang_thai', models.CharField(choices=[('queued', 'Đang chờ'), ('sending', 'Đang gửi'), ('sent', 'Đã gửi'), ('done', 'Hoàn thành'), ('failed', 'Lỗi')], db_index=True, default='queued', max_length=20)),
                ('thong_bao', models.TextField(blank=True)),
                ('ma_nhap_lieu', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Phiên nhập liệu',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.RenameIndex(
            model_name='ketquanhaplieu',
            new_name='nhap_lieu_k_ip_may_c8fd56_idx',
            old_name='nhap_lieu_k_ip_may_8ec80c_idx',
        ),
        migrations.RenameIndex(
            model_name='ketquanhaplieu',
            new_name='nhap_lieu_k_trang_t_63ea3c_idx',
            old_name='nhap_lieu_k_trang_t_d50c3f_idx',
        ),
        migrations.AddField(
            model_name='phiennhaplieu',
            name='chuong_trinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhap_lieu.chuongtrinhnhaplieu'),
        ),
        migrations.AddField(
            model_name='phiennhaplieu',
            name='may_tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhap_lieu.maytinh'),
        ),
        migrations.AddField(
            model_name='ketquanhaplieu',
            name='phien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_list', to='nhap_lieu.phiennhaplieu'),
        ),
        migrations.AddIndex(
            model_name='phiennhaplieu',
            index=models.Index(fields=['ip_may', '-ngay_tao'], name='nhap_lieu_p_ip_may_04f5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='phiennhaplieu',
            index=models.Index(fields=['trang_thai', '-ngay_tao'], name='nhap_lieu_p_trang_t_ed7d52_idx'),
        ),
    ]
