# Generated by Django 5.1.6 on 2025-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaresult',
            name='machine_number',
            field=models.CharField(max_length=100),
        ),
    ]
