# Generated by Django 5.1.6 on 2025-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0002_alter_qaresult_machine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaresult',
            name='operator_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='作業者名'),
        ),
    ]
