# Generated by Django 5.1.6 on 2025-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0003_qaresult_operator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaresult',
            name='match_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='一致率（％）'),
        ),
    ]
