# Generated by Django 5.1.6 on 2025-05-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0004_qaresult_match_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaresult',
            name='input_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='投入した材料の重さ (kg)'),
        ),
    ]
