# Generated by Django 5.1.6 on 2025-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0005_qaresult_input_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
