# Generated by Django 5.1.6 on 2025-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0006_qaresult_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadeviceinfo',
            name='compare_ratio',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5, verbose_name='画像とQR比較一致率(%)'),
        ),
    ]
