# Generated by Django 5.1.6 on 2025-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0007_qadeviceinfo_compare_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadeviceinfo',
            name='ratio',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='混合率'),
        ),
    ]
