# Generated by Django 5.1.6 on 2026-03-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhap_lieu', '0003_phiennhaplieu_and_more'),
        ('quet_anh', '0008_alter_qadeviceinfo_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAAutoInputLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64)),
                ('job_status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('job_message', models.TextField(blank=True, default='')),
                ('workstation_ip', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('ma_nhap_lieu', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='')),
                ('qa_machine_number', models.CharField(blank=True, default='', max_length=100)),
                ('qa_device_name', models.CharField(blank=True, default='', max_length=100)),
                ('qa_material', models.CharField(blank=True, default='', max_length=100)),
                ('qa_product', models.CharField(blank=True, default='', max_length=100)),
                ('qa_ratio', models.CharField(blank=True, default='', max_length=50)),
                ('qa_operator_name', models.CharField(blank=True, default='', max_length=100)),
                ('qa_result_status', models.CharField(blank=True, default='', max_length=255)),
                ('qa_match_ratio', models.FloatField(blank=True, null=True)),
                ('qa_input_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phien_nhap_lieu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_ledger', to='nhap_lieu.phiennhaplieu')),
                ('qa_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_input_ledgers', to='quet_anh.qaresult')),
            ],
            options={
                'verbose_name': 'Sổ cái job nhập liệu tự động',
                'verbose_name_plural': 'Sổ cái job nhập liệu tự động',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_status', '-created_at'], name='quet_anh_qa_job_sta_9528e8_idx'), models.Index(fields=['workstation_ip', '-created_at'], name='quet_anh_qa_worksta_904c97_idx'), models.Index(fields=['job_id'], name='quet_anh_qa_job_id_7e6e5e_idx')],
            },
        ),
    ]
