# Generated by Django 5.1.6 on 2026-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quet_anh", "0009_qaautoinputledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="qadeviceinfo",
            name="material_code",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="材料コード"),
        ),
    ]

