# Generated by Django 5.1.6 on 2026-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0010_qadeviceinfo_material_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAMaterialStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120, verbose_name='原材料名')),
                ('material_code', models.CharField(db_index=True, max_length=120, verbose_name='原材料コード')),
                ('stock_in_date', models.DateField(db_index=True, verbose_name='入庫日')),
                ('lot_color', models.CharField(choices=[('green', '緑'), ('black', '黒'), ('blue', '青'), ('red', '赤')], max_length=10, verbose_name='ロット識別色')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量(kg)')),
                ('bag_sequence_no', models.CharField(max_length=50, verbose_name='袋順番号')),
                ('lot_number', models.CharField(db_index=True, max_length=120, verbose_name='ロット番号')),
                ('workstation_management_no', models.CharField(blank=True, default='', max_length=120, verbose_name='端末管理番号')),
                ('supervisor_confirmed', models.BooleanField(default=False, verbose_name='上長確認')),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=120, verbose_name='上長名')),
                ('supervisor_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '原材料入庫台帳',
                'verbose_name_plural': '原材料入庫台帳',
                'ordering': ['-stock_in_date', '-id'],
            },
        ),
    ]
