# Generated by Django 5.1.6 on 2026-03-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0011_qamaterialstockledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamaterialstockledger',
            name='auto_input_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_ledger', to='quet_anh.qaautoinputledger', verbose_name='自動入力台帳'),
        ),
        migrations.AddField(
            model_name='qamaterialstockledger',
            name='qa_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_ledgers', to='quet_anh.qaresult', verbose_name='画像検査結果'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='bag_sequence_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='袋順番号'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='lot_color',
            field=models.CharField(choices=[('green', '緑'), ('black', '黒'), ('blue', '青'), ('red', '赤')], default='green', max_length=10, verbose_name='ロット識別色'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='lot_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='ロット番号'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='material_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='原材料コード'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='material_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='原材料名'),
        ),
        migrations.AlterField(
            model_name='qamaterialstockledger',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='重量(kg)'),
        ),
    ]
