# Generated by Django 5.1.6 on 2026-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0013_qamaterialoutstockledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaresult',
            name='lot_color',
            field=models.CharField(choices=[('green', '緑'), ('black', '黒'), ('blue', '青'), ('red', '赤')], default='green', max_length=10, verbose_name='ロット識別色'),
        ),
        migrations.AddField(
            model_name='qaresult',
            name='lot_number',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ロット番号'),
        ),
    ]
