# Generated by Django 5.1.6 on 2026-03-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0014_qaresult_lot_color_qaresult_lot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QADeletedJobMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '削除済みジョブ',
                'verbose_name_plural': '削除済みジョブ',
                'ordering': ['-created_at'],
            },
        ),
    ]
