# Generated by Django 5.1.6 on 2026-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0015_qadeletedjobmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAMaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(db_index=True, max_length=120, verbose_name='原材料名')),
                ('material_code', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='原材料コード')),
                ('qr_content', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='QR内容（短縮名）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '材料マスター',
                'verbose_name_plural': '材料マスター一覧',
                'ordering': ['material_name', 'material_code'],
            },
        ),
    ]
