# Generated by Django 5.1.6 on 2026-03-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0016_qamaterialmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qamaterialmaster',
            name='qr_content',
            field=models.CharField(db_index=True, max_length=120, verbose_name='QR内容（短縮名）'),
        ),
    ]
