# Generated by Django 5.1.6 on 2026-03-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0017_alter_qamaterialmaster_qr_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamaterialmaster',
            name='qr_content_in',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='入庫用QR内容'),
        ),
        migrations.AlterField(
            model_name='qamaterialmaster',
            name='qr_content',
            field=models.CharField(db_index=True, max_length=120, verbose_name='出庫用QR内容'),
        ),
    ]
