# Generated by Django 5.1.6 on 2026-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quet_anh', '0018_qamaterialmaster_qr_content_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamaterialmaster',
            name='bag_weight_kg',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='1袋重量(kg)'),
        ),
    ]
