"""
Django settings for trang_chu project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in ("1", "true", "yes", "on")


def env_list(name, default):
    value = os.getenv(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'your-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', ['192.168.10.250', 'localhost', '127.0.0.1'])

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', [
    'https://192.168.10.250',  # Thêm địa chỉ IP hoặc tên miền của bạn
    'http://192.168.10.250',
])

CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'trang_chu',
    'phe_duyet',
    'mente',
    'news',
    'baotri',
    'xu_ly_anh',
    'quet_anh',
    'django_extensions',
    'iot.apps.IotConfig',   # đổi từ 'iot'
    'nhap_lieu',
    'menu',
    'learn',
    'widget_tweaks',
    'setsubi_zaiko.apps.SetsubiZaikoConfig',
]
GTECH_DEV_APPS_ENABLED = True



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'learn.middleware.LearnAccessLogMiddleware',

]

ROOT_URLCONF = 'trang_chu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'trang_chu.context_processors.unread_messages_count',  # Thêm dòng này
                'trang_chu.context_processors.approve_button_count',  # Thêm dòng này
                'trang_chu.context_processors.japan_event',  # Thêm dòng này
                'trang_chu.context_processors.gtech_dev_apps',
                'learn.context_processors.pending_counts',  # Thêm dòng này
                'learn.context_processors.motivational_quotes',  # Thêm dòng này
            ],
        },
    },
]

WSGI_APPLICATION = 'trang_chu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv("SQLITE_DB_NAME", BASE_DIR / 'db.sqlite3'),
        'OPTIONS': {
            # Wait for locked writes instead of failing immediately.
            'timeout': 30,
        },
    }
}

if os.getenv("DB_ENGINE", "sqlite").lower() in ("postgres", "postgresql"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "seizo0"),
            "USER": os.getenv("POSTGRES_USER", "seizo0"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "seizo0"),
            "HOST": os.getenv("POSTGRES_HOST", "postgres"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "0")),
            "OPTIONS": {
                "connect_timeout": int(os.getenv("POSTGRES_CONNECT_TIMEOUT", "10")),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'sv10181.xserver.jp'
# EMAIL_PORT = 587  # Thử sử dụng cổng 587 thay vì 995
# EMAIL_USE_TLS = True  # Đảm bảo sử dụng TLS
# EMAIL_USE_SSL = False  # Đặt False nếu sử dụng TLS
# EMAIL_HOST_USER = 'pts@hayashi-p.co.jp'
# EMAIL_HOST_PASSWORD = 'Hayashi798701'
# DEFAULT_FROM_EMAIL = 'pts@hayashi-p.co.jp'
# EMAIL_TIMEOUT = 10  # tránh treo kết nối SMTP



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Giới hạn kích thước tệp tải lên (tính bằng byte)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Auto input: tách riêng chương trình xuất kho / nhập kho
NHAP_LIEU_XUAT_KHO_PROGRAM_NAME = "xuatkho"
NHAP_LIEU_NHAP_KHO_PROGRAM_NAME = "nhapkho"

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Địa chỉ Redis server
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CACHES['default']['LOCATION'] = os.getenv('REDIS_URL', CACHES['default']['LOCATION'])

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'dashboard_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.getenv('DASHBOARD_LOG_FILE', str(BASE_DIR / 'dashboard.log')),
            'encoding': 'utf8',
        },
    },
    'loggers': {
        'dashboard': {
            'handlers': ['dashboard_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
