# Generated by Django 5.1.6 on 2025-05-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('ratio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XuLyAnh2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.PositiveIntegerField(default=1, verbose_name='Số máy')),
                ('image', models.ImageField(upload_to='xu_ly_anh2/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='xu_ly_anh2/processed/')),
                ('data', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xu_ly_anh.deviceinfo', verbose_name='デバイス名')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
