# Generated by Django 5.1.6 on 2025-10-27 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_course_capacity_course_duration_course_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': '証明書', 'verbose_name_plural': '証明書'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'コース', 'verbose_name_plural': 'コース'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '登録', 'verbose_name_plural': '登録'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending_supervisor', '上司承認待ち'), ('pending_kanri', '管理者承認待ち'), ('approved', '承認済み'), ('rejected', '拒否')], default='pending_supervisor', help_text='登録のステータスを選択してください。', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='証明書ファイルをアップロードしてください。', null=True, upload_to='certificates/', verbose_name='証明書ファイル'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(help_text='証明書を発行する登録を選択してください。', on_delete=django.db.models.deletion.CASCADE, to='learn.enrollment', verbose_name='登録'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='証明書の発行日時を入力してください。', verbose_name='発行日時'),
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=25, help_text='コースの定員を入力してください。', verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='コースの詳細説明を入力してください。', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='コースの期間を入力してください。', max_length=100, verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='コースの終了日を選択してください。', null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, help_text='外部リンクがある場合は入力してください。', verbose_name='外部URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='コースがアクティブかどうかを選択してください。', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='コースの場所を入力してください。', max_length=100, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='コースの価格を入力してください。', max_digits=10, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='コースの開始日を選択してください。', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target',
            field=models.TextField(blank=True, help_text='コースの対象者を入力してください。', verbose_name='対象'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='コースのタイトルを入力してください。', max_length=200, verbose_name='コースタイトル'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False, help_text='コースが完了したかどうかを選択してください。', verbose_name='完了'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='コースの完了日時を入力してください。', null=True, verbose_name='完了日時'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='登録するコースを選択してください。', on_delete=django.db.models.deletion.CASCADE, to='learn.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, help_text='自動的に登録日時が設定されます。', verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='score',
            field=models.FloatField(blank=True, help_text='コースのスコアを入力してください。', null=True, verbose_name='スコア'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(help_text='登録するユーザーを選択してください。', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
