# Generated by Django 5.1.6 on 2025-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_enrollment_report_file_alter_enrollment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='comment',
            field=models.TextField(blank=True, help_text='承認または拒否の理由を入力してください。', null=True, verbose_name='コメント'),
        ),
    ]
