# Generated by Django 5.1.6 on 2025-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_enrollment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='comment',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='kanri_comment',
            field=models.TextField(blank=True, help_text='管理者の承認または拒否理由を入力してください。', null=True, verbose_name='管理者コメント'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='supervisor_comment',
            field=models.TextField(blank=True, help_text='上司の承認または拒否理由を入力してください。', null=True, verbose_name='上司コメント'),
        ),
    ]
