# Generated by Django 5.1.6 on 2025-10-27 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_remove_enrollment_comment_enrollment_kanri_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '承認'), ('reject', '拒否')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='learn.enrollment')),
            ],
            options={
                'verbose_name': '承認履歴',
                'verbose_name_plural': '承認履歴',
            },
        ),
    ]
