# Generated by Django 5.1.6 on 2025-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_approvalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='report_approved_by_kanri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='report_approved_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
