# Generated by Django 5.1.6 on 2025-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_remove_enrollment_kanri_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='report_kanri_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='report_status',
            field=models.CharField(choices=[('pending_supervisor', '上司承認待ち'), ('pending_kanri', '管理者承認待ち'), ('approved', '承認済み'), ('rejected', '拒否')], default='pending_supervisor', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='report_supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
