# Generated by Django 5.1.6 on 2025-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0', help_text='コースの価格を入力してください。', max_length=10, verbose_name='価格'),
        ),
    ]
