# Generated by Django 5.1.6 on 2025-10-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=100, help_text='コースの定員を入力してください。', verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0', help_text='コースの価格を入力してください。', max_length=100, verbose_name='価格'),
        ),
    ]
