# Generated by Django 5.1.6 on 2025-10-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_alter_course_capacity_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=1, help_text='コースの定員を入力してください。', verbose_name='定員'),
        ),
    ]
