# Generated by Django 5.1.6 on 2025-10-31 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_alter_course_capacity'),
        ('menu', '0005_alter_nhanvien_options_alter_nhanvien_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bang', models.CharField(choices=[('QC検定', 'QC検定'), ('電気系資格', '電気系資格'), ('プラスチック成形技能', 'プラスチック成形技能'), ('国家資格', '国家資格'), ('講習研修修了証', '講習研修修了証'), ('クレーン運転', 'クレーン運転'), ('日本語能力', '日本語能力'), ('英語能力', '英語能力'), ('中国語能力', '中国語能力'), ('IT関係資格', 'IT関係資格'), ('その他', 'その他')], max_length=32)),
                ('cap_do', models.CharField(choices=[('特急', '特急'), ('1級', '1級'), ('2級', '2級'), ('3級', '3級'), ('4級', '4級')], max_length=8)),
                ('file', models.FileField(upload_to='bangcap/')),
                ('ngay_cap', models.DateField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_caps', to='menu.nhanvien')),
            ],
        ),
    ]
