# Generated by Django 5.1.6 on 2025-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_bangcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='名言')),
                ('author', models.CharField(blank=True, default='匿名', max_length=100, verbose_name='著者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
