# Generated by Django 5.1.6 on 2025-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_motivationalquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='資料'),
        ),
    ]
