# Generated by Django 5.1.6 on 2026-03-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_course_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='q1_use_case',
            field=models.TextField(blank=True, default='', verbose_name='活用予定業務'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='q2_pre_issue',
            field=models.TextField(blank=True, default='', verbose_name='受講前課題'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='q3_post_state',
            field=models.TextField(blank=True, default='', verbose_name='受講後の状態'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='q4_purpose_summary',
            field=models.TextField(blank=True, default='', verbose_name='受講目的まとめ'),
        ),
    ]
