# Generated by Django 5.1.6 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_course_external_thumb_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '研修・講習', 'verbose_name_plural': '研修・講習'},
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=1, help_text='研修・講習の定員を入力してください。', verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='研修・講習の詳細説明を入力してください。', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='研修・講習の期間を入力してください。', max_length=100, verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='研修・講習の終了日を選択してください。', null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='研修・講習がアクティブかどうかを選択してください。', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='研修・講習の場所を入力してください。', max_length=100, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0', help_text='研修・講習の価格を入力してください。', max_length=100, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='研修・講習の開始日を選択してください。', null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target',
            field=models.TextField(blank=True, help_text='研修・講習の対象者を入力してください。', verbose_name='対象'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='研修・講習のタイトルを入力してください。', max_length=200, verbose_name='研修・講習タイトル'),
        ),
    ]
