# Generated by Django 5.1.6 on 2026-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0025_accesslog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangcap',
            name='loai_bang',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
