# Generated by Django 5.1.6 on 2025-06-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='休日の日付')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=8)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so', models.CharField(max_length=20, unique=True, verbose_name='社員番号')),
                ('ten', models.CharField(max_length=100, verbose_name='氏名')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=20, verbose_name='社員番号')),
                ('ten_nv', models.CharField(blank=True, max_length=100, verbose_name='氏名')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('ghi_chu', models.TextField(blank=True, verbose_name='備考')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ngay_giao', models.DateField()),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.monan')),
            ],
        ),
    ]
