# Generated by Django 5.1.6 on 2025-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ngay_giao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
