# Generated by Django 5.1.6 on 2025-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_order_ngay_giao'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calamviec',
            field=models.CharField(choices=[('日勤', '日勤'), ('夜勤', '夜勤')], default='日勤', max_length=10, verbose_name='勤務区分'),
        ),
    ]
