# Generated by Django 5.1.6 on 2025-10-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_calamviec'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='menu.nhanvien', verbose_name='Cấp trên phê duyệt'),
        ),
    ]
