# Generated by Django 5.1.6 on 2025-10-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_nhanvien_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員'},
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='menu.nhanvien', verbose_name='上司'),
        ),
    ]
