# Generated by Django 5.1.6 on 2025-10-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_nhanvien_options_alter_nhanvien_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
    ]
