# Generated by Django 5.1.6 on 2025-11-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_faxstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faxstatus',
            name='note',
        ),
    ]
