# Generated by Django 5.1.6 on 2025-11-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_faxstatus_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
