# Generated by Django 5.1.6 on 2025-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_nhanvien_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='gia2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
