# Generated by Django 5.1.6 on 2025-12-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_monan_gia2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='役職'),
        ),
    ]
