# Generated by Django 5.1.6 on 2026-03-13 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_nhanvien_chuc_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
