# Generated by Django 5.1.6 on 2025-03-04 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phe_duyet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'approver')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='documents/default.pdf', upload_to='documents/'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='level',
        ),
    ]
