# Generated by Django 5.1.6 on 2025-03-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phe_duyet', '0005_document_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
