# Generated by Django 5.1.6 on 2025-03-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phe_duyet', '0007_remove_document_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_file',
            field=models.FileField(blank=True, null=True, upload_to='approved_documents/'),
        ),
    ]
