# Generated by Django 5.1.6 on 2025-03-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phe_duyet', '0009_rename_created_at_document_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
