# Generated by Django 5.1.6 on 2025-03-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phe_duyet', '0010_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
